DELETE FROM SEAT_RESERVATION; 
DELETE FROM FARE; 
DELETE FROM LEG_INSTANCE; 
DELETE FROM FLIGHT_LEG; 
DELETE FROM FLIGHT; 
DELETE FROM AIRPORT 

 
 

DROP TABLE SEAT_RESERVATION CASCADE CONSTRAINTS; 
DROP TABLE FARE CASCADE CONSTRAINTS; 
DROP TABLE LEG_INSTANCE CASCADE CONSTRAINTS; 
DROP TABLE FLIGHT_LEG CASCADE CONSTRAINTS; 
DROP TABLE FLIGHT CASCADE CONSTRAINTS; 
DROP TABLE AIRPORT CASCADE CONSTRAINTS;
